#######################################################
####  ----------- The Variables Files ----------   ####
###   This file will hold all the variables used    ###
###           throughout this Terraform code        ###
####  ------------------------------------------   ####
#######################################################
#
# NOTE: every variable below has a default value, so this file works as-is
# with no changes needed. To override any default, do not edit this file
# directly - use the terraform.tfvars.example template provided in this
# folder instead. Copy it to terraform.tfvars, set the values you want to
# change, and Terraform will pick it up automatically.
#
# NOTE: every variable below also carries a validation block. Terraform
# checks each value against its rule before any resource is created. If a
# check fails, apply stops with a clear error message - no AWS resources
# are touched.
#
# NOTE ON AMI VARIABLES: os-ami-owner, os-ami-name, os-ami-virtualization-type,
# os-ami-architecture, and os-ami-root-device-type together define one AMI
# lookup in data.tf. Changing any one of them can affect what the others
# resolve to, so change these with care. See the README for a step-by-step
# guide on finding the right values before editing.
#
# NOTE ON REGION: aws-region defaults to eu-west-1 (Ireland). Changing it, in
# most cases, may require changing the AMI variables above, since a given Ubuntu
# release is not always published to every region at the same time. See
# the README for a step-by-step guide before changing this.
#
# NOTE ON KUBE NODE IP RANGES: vpc-cidr has a default and you may change it
# if you want. The nodes themselves, however, are not left to DHCP - each
# one gets a predetermined, fixed IP address. This is by design, so the IP
# schema stays predictable and every node's address is known and
# controlled rather than handed out automatically.
#
# Both subnets must stay /24:
#   - Public subnet (pub-sub-01-cidr): the bastion always takes .11.
#   - Private subnet (priv-sub-01-cidr): master nodes always take .11-.19
#     (9 addresses - enough for the 1/3/5 master counts this design
#     allows), worker nodes always take .21-.39 (19 addresses). This is
#     why kube-worker-count is capped at 19 - that is the entire usable
#     range.
#
# bastion-ip-host-num, kube-master-ip-start, and kube-worker-ip-start are
# declared as variables but are fixed by design, not user-configurable.
# The subnet CIDRs themselves CAN be overridden via terraform.tfvars (e.g.
# moved to different /24s), but these three host-offset variables cannot -
# their validation blocks reject any value other than their default, so
# an override attempt fails at plan time with an explanation rather than
# silently producing a broken IP layout.
#
#------------------------------------------------------

# First Region variables
#-----------------------
#
# NOTE: aws-region defaults to eu-west-1 (Ireland)
#
# List of AWS commercial regions this project supports. Excludes GovCloud
# and China regions, which use separate account partitions and are not
# reachable with a standard AWS provider setup. AWS adds new regions a
# few times a year - if aws-region below fails validation on a region you
# know exists, it may just be missing from this list; add it here.

# Region codes accepted by aws-region below, used in its validation block
locals {
  aws-supported-regions = [
    "us-east-1", "us-east-2", "us-west-1", "us-west-2",
    "af-south-1",
    "ap-east-1", "ap-south-1", "ap-south-2",
    "ap-northeast-1", "ap-northeast-2", "ap-northeast-3",
    "ap-southeast-1", "ap-southeast-2", "ap-southeast-3", "ap-southeast-4", "ap-southeast-5",
    "ca-central-1", "ca-west-1",
    "eu-central-1", "eu-central-2",
    "eu-west-1", "eu-west-2", "eu-west-3",
    "eu-north-1", "eu-south-1", "eu-south-2",
    "il-central-1",
    "me-south-1", "me-central-1",
    "sa-east-1",
  ]
}

variable "aws-region" {
  description = "AWS region to deploy into. Must be a supported AWS region (see the list in variables.tf). Defaults to eu-west-1 (Ireland)."
  type        = string
  default     = "eu-west-1"

  validation {
    condition     = contains(local.aws-supported-regions, var.aws-region)
    error_message = "aws-region must be a supported AWS commercial region, e.g. eu-west-1, us-east-1. See the list in variables.tf."
  }
}

#========================================

# Second Networking variables
#----------------------------
#
# NOTE: vpc-cidr defaults to 10.10.0.0/16
# NOTE: pub-sub-01-cidr defaults to 10.10.10.0/24
# NOTE: priv-sub-01-cidr defaults to 10.10.20.0/24
#
# pub-sub-01-cidr and priv-sub-01-cidr must each be a /24, and both must
# sit fully inside vpc-cidr. The /24 requirement exists because the fixed
# node IP offsets assume it (bastion at .11 in the public subnet; master
# .11-.19 and worker .21-.39 in the private subnet). The containment
# checks exist so a mismatched vpc-cidr and subnet CIDR fails at
# `terraform plan`, not as an opaque AWS API error mid-apply. The overlap
# check (on priv-sub-01-cidr) exists so the two subnets can never collide.
#
# Terraform has no built-in "is this CIDR inside that CIDR" function, so
# cidr-bounds below converts each CIDR's first and last address into a
# plain number, making "inside" and "overlap" simple numeric comparisons
# in the validation blocks further down.

locals {
  cidr-bounds = {
    for key, cidr in {
      vpc  = var.vpc-cidr
      pub  = var.pub-sub-01-cidr
      priv = var.priv-sub-01-cidr
    } : key => {
      first = sum([for i, octet in split(".", cidrhost(cidr, 0)) : tonumber(octet) * pow(256, 3 - i)])
      last  = sum([for i, octet in split(".", cidrhost(cidr, pow(2, 32 - tonumber(split("/", cidr)[1])) - 1)) : tonumber(octet) * pow(256, 3 - i)])
    }
  }
}

variable "vpc-cidr" {
  description = "CIDR block for the main VPC. Must be large enough to contain both subnets below."
  type        = string
  default     = "10.10.0.0/16"

  validation {
    condition     = can(cidrhost(var.vpc-cidr, 0))
    error_message = "vpc-cidr must be a valid CIDR block, e.g. 10.10.0.0/16."
  }
}

variable "pub-sub-01-cidr" {
  description = "CIDR block for the public subnet. Must be a /24 inside vpc-cidr - the bastion's fixed IP (.11) assumes it."
  type        = string
  default     = "10.10.10.0/24"

  validation {
    condition     = can(cidrhost(var.pub-sub-01-cidr, 0))
    error_message = "pub-sub-01-cidr must be a valid CIDR block, e.g. 10.10.10.0/24."
  }

  validation {
    condition     = tonumber(split("/", var.pub-sub-01-cidr)[1]) == 24
    error_message = "pub-sub-01-cidr must be a /24 - the bastion's fixed IP (.11) is sized for exactly one /24."
  }

  validation {
    condition = (
      local.cidr-bounds.pub.first >= local.cidr-bounds.vpc.first &&
      local.cidr-bounds.pub.last <= local.cidr-bounds.vpc.last
    )
    error_message = "pub-sub-01-cidr must fall entirely inside vpc-cidr."
  }
}

variable "priv-sub-01-cidr" {
  description = "CIDR block for the private subnet. Must be a /24 inside vpc-cidr - the fixed master (.11-.19) and worker (.21-.39) IP ranges assume it."
  type        = string
  default     = "10.10.20.0/24"

  validation {
    condition     = can(cidrhost(var.priv-sub-01-cidr, 0))
    error_message = "priv-sub-01-cidr must be a valid CIDR block, e.g. 10.10.20.0/24."
  }

  validation {
    condition     = tonumber(split("/", var.priv-sub-01-cidr)[1]) == 24
    error_message = "priv-sub-01-cidr must be a /24 - the fixed master and worker IP ranges are sized for exactly one /24."
  }

  validation {
    condition = (
      local.cidr-bounds.priv.first >= local.cidr-bounds.vpc.first &&
      local.cidr-bounds.priv.last <= local.cidr-bounds.vpc.last
    )
    error_message = "priv-sub-01-cidr must fall entirely inside vpc-cidr."
  }

  validation {
    condition = !(
      local.cidr-bounds.priv.first <= local.cidr-bounds.pub.last &&
      local.cidr-bounds.pub.first <= local.cidr-bounds.priv.last
    )
    error_message = "priv-sub-01-cidr must not overlap pub-sub-01-cidr."
  }
}

#========================================

# Third SSH Key variables
#--------------------------
#
# NOTE: ssh-file-name defaults to demo-ssh-key.pem
# NOTE: ec2-user-name defaults to ubuntu
#
# These control the SSH key file written locally by 10-compute.tf (with a
# random prefix added to the filename) and the default OS user baked into
# the Ubuntu AMI. Both are also used by the bastion's provisioners to copy
# the key onto the bastion and set its permissions - if you change
# ec2-user-name, make sure it matches the actual login user for whatever
# AMI os-ami-name resolves to.

variable "ssh-file-name" {
  description = "Local path to write the generated SSH private key to"
  type        = string
  default     = "demo-ssh-key.pem"

  validation {
    condition     = length(trimspace(var.ssh-file-name)) > 0
    error_message = "ssh-file-name cannot be empty."
  }
}

variable "ec2-user-name" {
  description = "Default SSH user for the Ubuntu AMI"
  type        = string
  default     = "ubuntu"

  validation {
    condition     = length(trimspace(var.ec2-user-name)) > 0
    error_message = "ec2-user-name cannot be empty."
  }
}

#========================================

# Fourth Bastion variables
#-------------------------
#
# NOTE: bastion-ip-host-num defaults to 11
# NOTE: bastion-node-size defaults to t3.micro
#
# bastion-ip-host-num is a host offset, not a literal address - the same
# pattern as kube-master-ip-start / kube-worker-ip-start below. 10-compute.tf
# derives the real IP with cidrhost(var.pub-sub-01-cidr, var.bastion-ip-host-num),
# so the bastion's address always tracks pub-sub-01-cidr even if that
# subnet is moved via terraform.tfvars. It is fixed by design, not meant
# to be overridden.

variable "bastion-ip-host-num" {
  description = "Host offset for the bastion's IP inside pub-sub-01-cidr. Fixed at 11 by design - do not override."
  type        = number
  default     = 11

  validation {
    condition     = var.bastion-ip-host-num == 11
    error_message = "bastion-ip-host-num is fixed at 11 by design and is not meant to be overridden."
  }
}

variable "bastion-node-size" {
  description = "EC2 instance type for the bastion host"
  type        = string
  default     = "t3.micro"

  validation {
    condition     = can(regex("^[a-z0-9]+\\.[a-z0-9]+$", var.bastion-node-size))
    error_message = "bastion-node-size must look like a valid EC2 instance type, e.g. t3.micro."
  }
}

#========================================

# Fifth Kubernetes cluster shape variables
# These control how many master and worker nodes get provisioned, and
# which Kubernetes distribution cloud-init installs on them.
#--------------------------------------------------------------------------
#
# NOTE: kube-master-count defaults to 1
# NOTE: kube-worker-count defaults to 2
# NOTE: k8s-distro defaults to kubeadm

variable "kube-master-count" {
  description = "Number of Kubernetes master (control-plane) nodes. Must be 1, 3, or 5 for a healthy etcd quorum. The fixed master IP range (.11-.19) has room for up to 9, but quorum rules cap it at 5."
  type        = number
  default     = 1

  validation {
    condition     = contains([1, 3, 5], var.kube-master-count)
    error_message = "kube-master-count must be 1, 3, or 5 (odd, for etcd quorum)."
  }
}

variable "kube-worker-count" {
  description = "Number of Kubernetes worker nodes. Minimum 1, maximum 19 - the fixed worker IP range (.21-.39) only has 19 usable addresses."
  type        = number
  default     = 2

  validation {
    condition     = var.kube-worker-count >= 1 && var.kube-worker-count <= 19
    error_message = "kube-worker-count must be between 1 and 19 - the fixed worker IP range (.21-.39) provides only 19 usable addresses."
  }
}

variable "k8s-distro" {
  description = "Kubernetes distribution to install on every node: kubeadm or rke2"
  type        = string
  default     = "kubeadm"

  validation {
    condition     = contains(["kubeadm", "rke2"], var.k8s-distro)
    error_message = "k8s-distro must be either \"kubeadm\" or \"rke2\"."
  }
}

#========================================

# Sixth Kube Node IP and sizing variables
# kube-master-ip-start and kube-worker-ip-start are fixed by design - see the
# NOTE ON KUBE NODE IP RANGES at the top of this file. Node N in a role gets
# <role-ip-start> + N (count.index), starting at index 0.
#-----------------------------------------------------------------------------
#
# NOTE: kube-master-ip-start defaults to 11
# NOTE: kube-worker-ip-start defaults to 21
# NOTE: kube-master-node-size defaults to t3.medium
# NOTE: kube-worker-node-size defaults to t3.xlarge
# NOTE: kube-node-disk-size defaults to 100

variable "kube-master-ip-start" {
  description = "Host offset for the first master node's IP inside priv-sub-01-cidr. Fixed at 11 by design - do not override."
  type        = number
  default     = 11

  validation {
    condition     = var.kube-master-ip-start == 11
    error_message = "kube-master-ip-start is fixed at 11 by design and is not meant to be overridden. Only priv-sub-01-cidr may be changed, and it must stay a /24."
  }
}

variable "kube-worker-ip-start" {
  description = "Host offset for the first worker node's IP inside priv-sub-01-cidr. Fixed at 21 by design - do not override."
  type        = number
  default     = 21

  validation {
    condition     = var.kube-worker-ip-start == 21
    error_message = "kube-worker-ip-start is fixed at 21 by design and is not meant to be overridden. Only priv-sub-01-cidr may be changed, and it must stay a /24."
  }
}

variable "kube-master-node-size" {
  description = "EC2 instance type for the Kube master node(s)"
  type        = string
  default     = "t3.medium"

  validation {
    condition     = can(regex("^[a-z0-9]+\\.[a-z0-9]+$", var.kube-master-node-size))
    error_message = "kube-master-node-size must look like a valid EC2 instance type, e.g. t3.medium."
  }
}

variable "kube-worker-node-size" {
  description = "EC2 instance type for the Kube worker nodes"
  type        = string
  default     = "t3.xlarge"

  validation {
    condition     = can(regex("^[a-z0-9]+\\.[a-z0-9]+$", var.kube-worker-node-size))
    error_message = "kube-worker-node-size must look like a valid EC2 instance type, e.g. t3.xlarge."
  }
}

variable "kube-node-disk-size" {
  description = "Root volume size in GB for each Kube node"
  type        = number
  default     = 100

  validation {
    condition     = var.kube-node-disk-size >= 20
    error_message = "kube-node-disk-size must be at least 20 GB."
  }
}

#========================================

# Seventh OS AMI variables
# These five variables together define which single AMI data.aws_ami (in
# data.tf) resolves to - see the NOTE ON AMI VARIABLES at the top of this
# file before changing any of them.
#-------------------------------------------------------------------------
#
# NOTE: os-ami-owner defaults to 099720109477 (Canonical)
# NOTE: os-ami-name defaults to ubuntu/images/hvm-ssd-gp3/ubuntu-resolute-26.04-amd64-server-*
# NOTE: os-ami-virtualization-type defaults to hvm
# NOTE: os-ami-architecture defaults to x86_64
# NOTE: os-ami-root-device-type defaults to ebs

variable "os-ami-owner" {
  description = "AWS account ID that owns the AMI (099720109477 for official Canonical Ubuntu AMIs)"
  type        = string
  default     = "099720109477"

  validation {
    condition     = can(regex("^[0-9]{12}$", var.os-ami-owner))
    error_message = "os-ami-owner must be a 12-digit AWS account ID."
  }
}

variable "os-ami-name" {
  description = "Name filter for the AMI lookup - set to the release you want, e.g. ubuntu-jammy-22.04 or ubuntu-noble-24.04"
  type        = string
  default     = "ubuntu/images/hvm-ssd-gp3/ubuntu-resolute-26.04-amd64-server-*"

  validation {
    condition     = length(trimspace(var.os-ami-name)) > 0
    error_message = "os-ami-name cannot be empty."
  }
}

variable "os-ami-virtualization-type" {
  description = "Virtualization type filter for the AMI lookup"
  type        = string
  default     = "hvm"

  validation {
    condition     = contains(["hvm", "paravirtual"], var.os-ami-virtualization-type)
    error_message = "os-ami-virtualization-type must be either \"hvm\" or \"paravirtual\"."
  }
}

variable "os-ami-architecture" {
  description = "Architecture filter for the AMI lookup"
  type        = string
  default     = "x86_64"

  validation {
    condition     = contains(["x86_64", "arm64", "i386"], var.os-ami-architecture)
    error_message = "os-ami-architecture must be one of: x86_64, arm64, i386."
  }
}

variable "os-ami-root-device-type" {
  description = "Root device type filter for the AMI lookup"
  type        = string
  default     = "ebs"

  validation {
    condition     = contains(["ebs", "instance-store"], var.os-ami-root-device-type)
    error_message = "os-ami-root-device-type must be either \"ebs\" or \"instance-store\"."
  }
}

#========================================
